#
# Compose file to run the voting app and dependent services
#

version: '3'

services:
  web-vote-app:
    image: python:2.7-slim
    build: web-vote-app
    environment:
      WEB_VOTE_NUMBER: "01"
      constraint:node: "=frontend01"
    replica: 3

  vote-worker:
    image: bitnami/java:17.0.0
    build: vote-worker
    environment:
      FROM_REDIS_HOST: 1
      TO_REDIS_HOST: 1
    replica: 3

  results-app:
    image: node:10.0.0-alpine
    build: results-app
    replica: 3

  redis01:
    image: redis:3
    replica: 3

  store:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg8675309
    replica: 3
